export const PLANT_DATA_PATH = "PLANT_DATA_PATH"
export const LEAF_DATA_PATH = "LEAF_DATA_PATH"
export const HANDLE_DELETE_PLANT_CHECKED ="HANDLE_DELETE_PLANT_CHECKED"
export const HANDLE_ADD_PLANT_CHECKED ="HANDLE_ADD_PLANT_CHECKED"
export const  GENERATED_XAXUS_DATA = 'GENERATED_XAXUS_DATA'
export const  ADD_PLANT_PARAMETERS = 'ADD_PLANT_PARAMETERS'